# Generated by Django 3.2.2 on 2021-05-16 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_name', models.CharField(default=None, editable=False, help_text='Please enter your name', max_length=255)),
                ('unique_id', models.CharField(default=None, editable=False, help_text='Donor ID', max_length=100, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10)])),
                ('contact_number', models.CharField(editable=False, max_length=255, unique=True)),
                ('blood_group', models.CharField(editable=False, help_text="Enter donor's blood group", max_length=10)),
                ('city', models.CharField(editable=False, help_text='Which city will you be at the time of donation', max_length=255)),
                ('time_post_recovery', models.CharField(choices=[('Less than 5 days', 'Less than 5 days'), ('5 to 15 days', '5 to 15 days'), ('15 to 30 days', '15 to 30 days'), ('30 days to 4 months', '30 days to 4 months'), ('Greater than 4 months', 'Greater than 4 months')], help_text='Please select the time passed since recovery', max_length=255)),
                ('num_days', models.IntegerField(help_text='Please enter the number of days since recovery')),
                ('email', models.EmailField(help_text='Please enter your email id', max_length=255)),
                ('has_donated', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Cannot donate', 'Cannot donate')], help_text='Has the person donated?', max_length=255)),
                ('comments', models.CharField(max_length=255)),
            ],
        ),
    ]
